---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-deployment
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      labels:
        app: weather
    spec:
      restartPolicy: Always
      containers:
      - name: weather
        image: oscarsotosanchez/weatherservice:v1.0
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "250m"
        env:
        - name: GRPC_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: GRPC_PORT
          value: "9090"
        ports:
        - containerPort: 9090
  replicas: 1

---
apiVersion: v1
kind: Service
metadata:
  name: weather-service
  labels:
    app: weather
spec:
  selector:
    app: weather
  ports:
  - port: 9090
    targetPort: 9090
  type: ClusterIP
