---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: topo-deployment
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: topo
  template:
    metadata:
      labels:
        app: topo
    spec:
      restartPolicy: Always
      containers:
      - name: topo
        image: oscarsotosanchez/toposervice:v1.0
        env:
        - name: SPRING_DATA_MONGODB_HOST
          value: mongodb-service
        - name: SPRING_DATA_MONGODB_PORT
          value: "27017"
        - name: SPRING_DATA_MONGODB_DATABASE
          value: topoDB
        - name: SPRING_DATA_MONGODB_AUTHENTICATION-DATABASE
          value: admin
        - name: SPRING_DATA_MONGODB_USERNAME
          value: root
        - name: SPRING_DATA_MONGODB_PASSWORD
          value: password
        - name: SERVER_PORT
          value: "8080"
        ports:
        - containerPort: 8080
  replicas: 1

---
apiVersion: v1
kind: Service
metadata:
  name: topo-service
  labels:
    app: topo
spec:
  selector:
    app: topo
  ports:
  - port: 8080
    targetPort: 8080
    name: topo-port